name: CI

on:
  pull_request:
    branches:
      - '*'

env:
  SERVER_PORT: 3000
  GRAPHQL_SCHEMA_DIR: ./api/graphql
  WEATHER_API_KEY: super-secret-key
  WEATHER_FORECAST_API_URL: http://localhost:3001/data/2.5/onecall
  WEATHER_LOCATION_API_URL: http://localhost:3001/geo/1.0/direct

jobs:
  install-dep:
    name: Install and cache dependencies
    strategy:
      fail-fast: true
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

  format:
    name: Format
    strategy:
      fail-fast: true
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    needs:
      - install-dep

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Format
        run: yarn format

    timeout-minutes: 5

  lint:
    name: Lint
    strategy:
      fail-fast: true
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - install-dep

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

    timeout-minutes: 5

  spellcheck:
    name: Spellcheck
    strategy:
      fail-fast: true
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - install-dep

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn spellcheck

    timeout-minutes: 5

  typecheck:
    name: Typecheck
    strategy:
      fail-fast: true
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - install-dep

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Typecheck
        run: yarn typecheck

    timeout-minutes: 5

  test:
    name: Test
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    needs:
      - typecheck
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test

  test-e2e:
    name: E2E-Test
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    needs:
      - typecheck
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Mock OpenWeatherAPI Docker image
        run:
          docker build -t openweather-api-mock -f
          ./docker/Dockerfile.openweather ./

      - name: Run Mock OpenWeatherAPI Docker image
        run:
          docker run -d --name openweather-api -p 3001:3001 openweather-api-mock

      - name: Test
        run: yarn test:e2e
